env:
  global:
    - CC_TEST_REPORTER_ID=0f5097f9008192684ae5748e841b38d1b41496eb17d6e79749ce3c2e565e459b


language: python
python: "3.5.5"
cache: pip
addons:
    postgresql: "9.6"

install:
  - export PROJECT_DIR=`pwd`
  - cd /tmp
  - git clone https://github.com/uclouvain/osis-portal.git --depth=1 --recurse-submodules --single-branch --branch dev
  - cd osis-portal
  - pip install -r requirements.txt
  - rm -Rf continuing_education
  - ln -s $PROJECT_DIR continuing_education

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python3 manage.py compilemessages && coverage run manage.py test continuing_education --exclude-tag=selenium

after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
