# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0002_auto_20180918_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='formation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
