# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0002_continuingeducationperson'),
        ('continuing_education', '0003_admission_formation'),
    ]

    operations = [
    ]
