# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0014_auto_20181126_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='state_reason',
            field=models.TextField(blank=True, verbose_name='State reason'),
        ),
    ]
