# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 08:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0015_admission_state_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroupYear', verbose_name='Formation'),
        ),
    ]
