# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0017_auto_20190124_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='use_address_for_billing',
            field=models.BooleanField(default=True, verbose_name='Use address for billing'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='use_address_for_post',
            field=models.BooleanField(default=True, verbose_name='Use address for post'),
        ),
    ]
