# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-01 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0018_auto_20190128_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='registration_complete',
            new_name='ucl_registration_complete',
        ),
    ]
