# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-10 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0025_auto_20190404_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='person_information',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='residence_address',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='birth_country',
        ),
        migrations.RemoveField(
            model_name='continuingeducationperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='continuingeducationtraining',
            name='education_group',
        ),
        migrations.RemoveField(
            model_name='continuingeducationtraining',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='persontraining',
            name='person',
        ),
        migrations.RemoveField(
            model_name='persontraining',
            name='training',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='ContinuingEducationPerson',
        ),
        migrations.DeleteModel(
            name='ContinuingEducationTraining',
        ),
        migrations.DeleteModel(
            name='PersonTraining',
        ),
    ]
