# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0026_auto_20190411_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='professional_impact',
        ),
        migrations.AddField(
            model_name='admission',
            name='professional_personal_interests',
            field=models.TextField(blank=True, verbose_name='Professional and personal interests'),
        ),
    ]
