# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-15 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuing_education', '0027_auto_20190412_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='awareness_ucl_website',
            field=models.BooleanField(default=False, verbose_name='By UCLouvain website'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='previous_ucl_registration',
            field=models.BooleanField(default=False, verbose_name='Previous UCLouvain registration'),
        ),
    ]
